    pipeline {
        agent any
        stages {
            stage('Build Application') {
                steps {
                    sh 'mvn -f school/pom.xml clean package'
                }
                post {
                    success {
                        echo "Now Archiving the Artifacts...."
                        archiveArtifacts artifacts: '**/*.war'
                    }
                }
            }
     
            stage('Create Tomcat Docker Image'){
                steps {
                    sh "docker build ./school -t tomcatschool:${env.BUILD_ID}"
                }
            }
     
        }
    }